/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5b527abf-f17e-4852-9534-8c1c021b5748",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qd1ZvQdml",
    "aws_user_pools_web_client_id": "4ivnp2ogv9rd7d5jg4q59fd5ir",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://khvia54wkbg2te443peadebuhq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ebhq4u6y35gfzkk7argbs2m26m"
};


export default awsmobile;
